---
title: "EBV"
date: August 24, 2023
output:
  BiocStyle::html_document:
      toc: true
package: methylkey
params:
  mks : "EBV_corrected_2023-08-24.rds"
  group: "EBV"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE)

source("/luca/git/methylkey/R/regression.r")
source("/luca/git/methylkey/R/plot.r")
#library(DescTools)
#library(DT)

#dbs<-initEnrichR("hg19")

output_dir<-"EBV"
dir.create(output_dir)
```


```{r loading_data}
# load betas
se<-readRDS(params$mks)

grp_g=colData(se) %>% pull(tolower(params$group))
Sentrix_Position=colData(se) %>% pull(sentrix_position)
model = "~ebv"
method = "ls"
niter=10
ncore=2
pdata=colData(se)
betas=getBetas(se, na=FALSE, sex=FALSE)
mvals=getMval(se, sex=FALSE)

manifest <- getAnnotedManifest( metadata(se)$plateform ) %>% plyr::rename(replace = c(Name="probeID"), warn_missing = FALSE)
```

# Models

```{r, echo=FALSE, warning=FALSE, error=FALSE, results='asis'}
regression<-m_regression(mvals, pdata, model, method=method, niter=niter, ncore=ncore )
deltaBetas<-getDeltaBetas(betas[rownames(regression$table),],grp_g,case,control)*100

table<-data.frame(probeID=rownames(regression$table), regression$table, deltabetas=deltaBetas) %>%
dplyr::select("probeID","P.Value","adj.P.Val","t","Coefficient","Stdev","deltabetas") %>%
    separate(probeID, sep="_", into=c("probeID","x"),remove=TRUE, fill="right") %>%
    dplyr::mutate(status=ifelse(deltabetas>0,"hyper","hypo")) %>%
    dplyr::mutate(is.sig=adj.P.Val<qval) %>%
    merge(manifest, by="probeID") %>%
    tidyr::unite("probeID", c(probeID,x),sep="_", na.rm=TRUE, remove=TRUE) %>%
    dplyr::arrange(desc(adj.P.Val))
    
  write_tsv(table, file=paste0(output, "_", Sys.Date(), ".dmps.csv"))

  #qqplot
  cat(paste0("nb dmps=",regression$table %>% filter(adj.P.Val < qval) %>% nrow()))
  qqman::qq(regression$pvals,main=paste("QQ plot: ","lambda=", regression$lambda,sep=""))
  
  #toptable
  cat(paste0("\n\n#",level," TopTable (500 max) \n\n"))
  table %>% dplyr::filter(adj.P.Val < qval) %>% head(500) %>% DT::datatable() %>% htmltools::tagList() %>% print()
  
  #plots
  cat(paste0("\n\n#",level," DeltaBetas distribution\n\n"))
  deltaBetas<-deltaBetas[ regression$table$adj.P.Val< qval ]
  if (length(deltaBetas)>0) { hist(deltaBetas, col="chocolate" ) }

  cat(paste0("\n\n#",level," Volcano plot\n\n"))
  print(methylkey::volcano(table))
  
  cat(paste0("\n\n#",level," Manhattan plot\n\n"))
  print(methylkey::manhattan(table))
  
  cat(paste0("\n\n#",level," Barplots\n\n"))
  barplots_(plateform=plateform,table,manifest)
```

