---
title: "PCA"
output: flexdashboard::flex_dashboard
params:
  meth: "/data/ege/Waterpipe/work/cahaisv/waterpipe/Funnorm/mval.rda"
---

```{r echo = FALSE, message = FALSE}
library(data.table)
library(RColorBrewer)
library(formattable)
library(flexdashboard)
```

```{r setup, include=FALSE}
load(params$meth)
```

# 1 {.tabset .tabset-fade .tabset-pills}

## Betas {.tabset .tabset-fade .tabset-pills}

### Contrib betas

```{r beta_contrib, fig.width=10, fig.height=7}
plot(analyse$betas_pca$contrib)
```

### pvalues betas

```{r beta_pval, echo = FALSE, results='asis', fig.height=4}
pvalue<-as.data.table(analyse$betas_pca$pval)
sig_pvalue_bold <- formatter("span", style = x ~ style("background-color" = ifelse(x <= 1e-5, "pink", ifelse(x <= 0.05, "palegoldenrod", "transparent"))))
pvalue<-cbind(rownames(analyse$betas_pca$pval),pvalue)
formattable(pvalue, list(area(col = names(pvalue)[-1]) ~ sig_pvalue_bold ))
```

### qvalues betas

```{r beta_qval, echo = FALSE, results='asis', fig.height=4}
qvalue<-as.data.table(analyse$betas_pca$qval)
sig_qvalue_bold <- formatter("span", style = x ~ style("background-color" = ifelse(x <= 0.05, "pink", ifelse(x <= 0.1, "palegoldenrod", "transparent"))))
qvalue<-cbind(rownames(analyse$betas_pca$qval),qvalue)
formattable(qvalue, list(area(col = names(qvalue)[-1]) ~ sig_pvalue_bold ))
```

## Mvalues {.tabset .tabset-fade .tabset-pills}

### Contrib Mvalues

```{r mval_contrib, fig.width=10, fig.height=7}
plot(analyse$mval_pca$contrib)
```

### pvalues Mvalues

```{r mval_pval, echo = FALSE, results='asis', fig.height=4}
pvalue<-as.data.table(analyse$mval_pca$pval)
sig_pvalue_bold <- formatter("span", style = x ~ style("background-color" = ifelse(x <= 1e-5, "pink", ifelse(x <= 0.05, "palegoldenrod", "transparent"))))
pvalue<-cbind(rownames(analyse$mval_pca$pval),pvalue)
formattable(pvalue, list(area(col = names(pvalue)[-1]) ~ sig_pvalue_bold ))
```

### qvalues Mvalues

```{r mval_qval, echo = FALSE, results='asis', fig.height=4}
qvalue<-as.data.table(analyse$mval_pca$qval)
sig_qvalue_bold <- formatter("span", style = x ~ style("background-color" = ifelse(x <= 0.05, "pink", ifelse(x <= 0.1, "palegoldenrod", "transparent"))))
qvalue<-cbind(rownames(analyse$mval_pca$qval),qvalue)
formattable(qvalue, list(area(col = names(qvalue)[-1]) ~ sig_pvalue_bold ))
```

