#' Generate a Venn diagram for DMRs based on shared probes
#'
#' This function builds a Venn diagram comparing DMRs
#'   identified by different tools, based on shared probe membership.
#'   Two DMRs are considered linked if they share at least one probe.
#'
#' @param dt A data.frame or tibble containing at least these columns:
#'   tool, ID, probes
#' @return A ggplot object generated by ggvenn. Returns NULL if fewer than
#'   two tools have data.
#' @importFrom tidyr separate_longer_delim
#' @importFrom dplyr select mutate filter distinct pull
#' @importFrom igraph graph_from_data_frame components
#' @importFrom ggvenn ggvenn
#' @export
tools_venn <- function(dt) {
  if (!is.data.frame(dt)) {
    stop("dt must be a data.frame or tibble.")
  }
  required_cols <- c("tool", "ID", "probes")
  if (!all(required_cols %in% names(dt))) {
    stop("dt must contain columns: tool, ID and probes.")
  }

  dt <- dt |>
    tidyr::separate_longer_delim("probes", delim = ";")

  edges <- dt |>
    dplyr::select("ID", "probes") |>
    dplyr::mutate(
      probes = trimws(as.character(.data$probes)),
      ID = trimws(as.character(.data$ID))
    ) |>
    dplyr::filter(
      !is.na(.data$probes), .data$probes != "",
      !is.na(.data$ID), .data$ID != ""
    ) |>
    dplyr::distinct(.data$probes, .data$ID)

  if (nrow(edges) == 0) {
    return(NULL)
  }

  g <- igraph::graph_from_data_frame(edges, directed = FALSE)
  clusters <- igraph::components(g)$membership

  dt_clustered <- dt |>
    dplyr::mutate(Cluster_ID = clusters[.data$ID]) |>
    dplyr::distinct(.data$Cluster_ID, .data$tool)

  a <- list(
    `dmrcate` = dt_clustered |>
      dplyr::filter(.data$tool == "dmrcate") |>
      dplyr::pull("Cluster_ID"),
    `dmrff` = dt_clustered |>
      dplyr::filter(.data$tool == "dmrff") |>
      dplyr::pull("Cluster_ID"),
    `combp` = dt_clustered |>
      dplyr::filter(.data$tool == "combp") |>
      dplyr::pull("Cluster_ID"),
    `ipdmr` = dt_clustered |>
      dplyr::filter(.data$tool == "ipdmr") |>
      dplyr::pull("Cluster_ID")
  )

  a <- a[sapply(a, length) > 0]
  if (length(a) < 2) return(NULL)

  ggvenn::ggvenn(a, names(a))
}

#' Create a density plot of DMR lengths grouped by dmrtool
#'
#' This function generates a density plot of DMR
#'   (Differentially Methylated Region) lengths grouped by 'dmrtool'.
#'   It takes a data frame 'dt' as input, calculates the length of each DMR,
#'   and then creates the density plot.
#'
#' @param dt A data frame containing the data.
#'
#' @return A ggplot2 density plot showing DMR length distributions
#'   grouped by 'dmrtool'.
#'
#' @importFrom dplyr filter group_by summarise mutate
#' @importFrom tidyr extract
#' @importFrom ggpubr ggdensity
#' @importFrom ggplot2 scale_x_continuous
#'
#' @export
tools_density <- function(dt) {

  dt |>
    dplyr::filter(!is.na(.data$ID)) |>
    dplyr::group_by(.data$tool, .data$ID) |>
    dplyr::summarise(no.cpgs = dplyr::n(), .groups = "drop") |>
    tidyr::extract(
      .data$ID,
      into = c("chr", "start", "end"),
      regex = "^([^-]+)-(\\d+)-(\\d+)(?:-.*)?$"
    ) |>
    dplyr::mutate(
      start = as.numeric(start),
      end = as.numeric(end)
    ) |>
    dplyr::filter(!is.na(start), !is.na(end)) |>
    dplyr::mutate(length = end - start) |>
    dplyr::filter(length > 0) |>
    ggpubr::ggdensity(
      x = "length",
      add = "mean", rug = TRUE,
      color = "tool", fill = "tool",
      palette = c("#00AFBB", "#E7B800", "#FC4E07", "#59981A"),
      title = "D"
    ) +
    ggplot2::scale_x_continuous(trans = "log2")
}


#' Create a violin plot of DMR lengths grouped by dmrtool
#'
#' This function generates a violin plot of DMR
#'   (Differentially Methylated Region) lengths grouped
#'   y 'dmrtool'. It takes a data frame 'dt' as input,
#'   calculates the length of each DMR, and then creates the violin plot.
#'
#' @param dt A data frame containing the data.
#'
#' @return A ggplot2 violin plot showing DMR length
#'   distributions grouped by 'dmrtool'.
#'
#' @importFrom dplyr mutate filter group_by
#' @importFrom ggpubr ggviolin
#'
#' @export
my_violin <- function(dt) {
  dt |>
    dplyr::filter(!is.na(.data$ID)) |>
    dplyr::group_by(.data$tool, .data$ID) |>
    dplyr::filter(!is.na(start), !is.na(end)) |>
    dplyr::mutate(length = end - start) |>
    dplyr::filter(length > 0) |>
    ggpubr::ggviolin(
      x = "tool", y = "length", fill = "tool",
      palette = c("#00AFBB", "#E7B800", "#FC4E07", "#59981A"),
      title = "E"
    )
}
