#' Generate a Venn diagram for DMRs based on shared probes
#'
#' @description
#' This function builds a Venn diagram comparing DMRs identified by
#' different tools, based on shared probe membership.
#' Two DMRs are considered linked if they share at least one probe.
#'
#' @param dt A data.frame or tibble containing at least these columns:
#' \itemize{
#'   \item \code{Probe_ID}: probe identifier (e.g. cg00002033).
#'   \item \code{dmrtool}: name of the tool (dmrcate, dmrff, combp,
#'     ipdmr).
#'   \item \code{ID}: DMR region identifier (e.g.
#'     chr19-39307110-39307923).
#' }
#'
#' @details
#' The function uses the result table where each probe is linked to a DMR.
#' DMRs sharing a probe are grouped into connected clusters using igraph.
#' The Venn diagram then compares the clusters detected by each tool.
#'
#' @return A \code{ggplot} object generated by \code{ggvenn}.
#'   Returns \code{NULL} if fewer than two tools have data.
#'
#' @note
#' \code{igraph::components} handles cases where tool boundaries are
#' slightly offset but biologically connected.
#'
#' @export
tools_venn <- function(dt) {
  if (!is.data.frame(dt)) {
    stop("dt must be a data.frame or tibble.")
  }
  required_cols <- c("tool", "ID", "probes")
  if (!all(required_cols %in% names(dt))) {
    stop("dt must contain columns: tool, ID and probes.")
  }

  dt <- dt |>
    tidyr::separate_rows(probes,  sep = ";")

  edges <- dt |>
    dplyr::select(ID, probes) |>
    dplyr::mutate(
      probes = trimws(as.character(probes)),
      ID = trimws(as.character(ID))
    ) |>
    dplyr::filter(
      !is.na(probes), probes != "",
      !is.na(ID), ID != ""
    ) |>
    dplyr::distinct(probes, ID)

  if (nrow(edges) == 0) {
    return(NULL)
  }

  g <- igraph::graph_from_data_frame(edges, directed = FALSE)
  clusters <- igraph::components(g)$membership

  dt_clustered <- dt |>
    dplyr::mutate(Cluster_ID = clusters[ID]) |>
    dplyr::distinct(Cluster_ID, tool)

  a <- list(
    `DMRcate` = dt_clustered |>
      dplyr::filter(tool == "dmrcate") |>
      dplyr::pull(Cluster_ID),
    `DMRff` = dt_clustered |>
      dplyr::filter(tool == "dmrff") |>
      dplyr::pull(Cluster_ID),
    `combp` = dt_clustered |>
      dplyr::filter(tool == "combp") |>
      dplyr::pull(Cluster_ID),
    `ipdmr` = dt_clustered |>
      dplyr::filter(tool == "ipdmr") |>
      dplyr::pull(Cluster_ID)
  )

  a <- a[sapply(a, length) > 0]
  if (length(a) < 2) return(NULL)

  ggvenn::ggvenn(a, names(a))
}

#' Create a density plot of DMR lengths grouped by dmrtool
#'
#' This function generates a density plot of DMR (Differentially Methylated Region) lengths grouped by 'dmrtool'. It takes a data frame 'dt' as input, calculates the length of each DMR, and then creates the density plot.
#'
#' @param dt A data frame containing the data.
#'
#' @return A ggplot2 density plot showing DMR length distributions grouped by 'dmrtool'.
#'
#' @export
tools_density <- function(dt) {

  dt |>
    dplyr::filter(!is.na(ID)) |>
    dplyr::group_by(tool, ID) |>
    dplyr::summarise(no.cpgs = n(), .groups = 'drop') |>
    tidyr::extract(
      ID,
      into = c("chr", "start", "end"),
      regex = "^([^-]+)-(\\d+)-(\\d+)(?:-.*)?$"
    ) |>
    dplyr::mutate(
      start = as.numeric(start),
      end = as.numeric(end)
    ) |>
    dplyr::filter(!is.na(start), !is.na(end)) |>
    dplyr::mutate(length = end - start) |>
    dplyr::filter(length > 0) |>
    ggpubr::ggdensity(
      x = "length",
      add = "mean", rug = TRUE,
      color = "tool", fill = "tool",
      palette = c("#00AFBB", "#E7B800", "#FC4E07", "#59981A"),
      title = "D"
    ) +
    ggplot2::scale_x_continuous(trans = 'log2')
}


#' Create a violin plot of DMR lengths grouped by dmrtool
#'
#' This function generates a violin plot of DMR
#'   (Differentially Methylated Region) lengths grouped
#'   y 'dmrtool'. It takes a data frame 'dt' as input,
#'   calculates the length of each DMR, and then creates the violin plot.
#'
#' @param dt A data frame containing the data.
#'
#' @return A ggplot2 violin plot showing DMR length
#'   distributions grouped by 'dmrtool'.
#'
#' @export
my_violin <- function(dt) {
  dt |>
    dplyr::filter(!is.na(ID)) |>
    dplyr::group_by(tool, ID) |>
    dplyr::filter(!is.na(start), !is.na(end)) |>
    dplyr::mutate(length = end - start) |>
    dplyr::filter(length > 0) |>
    ggpubr::ggviolin(
      x = "tool", y = "length", fill = "tool",
      palette = c("#00AFBB", "#E7B800", "#FC4E07", "#59981A"),
      title = "E"
    )
}
